apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hlng42v3d-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:d03337365184a874c2aff55246b6dcba90d7c312@sha256:b2fd5b2bcf5a30bc00a66c42809d1e00083b52d8068fd32cd8e56bda1e05cb87
          name: container-image
